// This file was autogenerated by vendor/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/demo.js', ['ZH.demo'], ['goog.ui.Component']);
goog.addDependency('../../../../src/live_component.js', ['ZH.ui.LiveComponent', 'ZH.ui.LiveComponent.Error', 'ZH.ui.LiveComponent.EventType', 'ZH.ui.LiveComponent.State'], ['ZH.core.LiveComponentPlugin', 'ZH.core.Registry', 'ZH.core.uti', 'goog.array', 'goog.asserts', 'goog.dom', 'goog.dom.NodeType', 'goog.events.EventHandler', 'goog.events.EventTarget', 'goog.object', 'goog.structs.Map', 'goog.style', 'goog.ui.IdGenerator']);
goog.addDependency('../../../../src/plugin.js', ['ZH.core.LiveComponentPlugin'], ['goog.events.EventTarget', 'goog.functions', 'goog.log', 'goog.object', 'goog.reflect']);
goog.addDependency('../../../../src/registry.js', ['ZH.core.Registry'], ['goog.array', 'goog.array.ArrayLike', 'goog.debug.Logger', 'goog.debug.TextFormatter', 'goog.dom', 'goog.structs.Map']);
goog.addDependency('../../../../src/uti.js', ['ZH.core.uti'], ['goog.array', 'goog.json', 'goog.string', 'goog.style']);
