// This file was autogenerated by vendor/google-closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/demo.js', ['ZH.demo'], ['goog.ui.Component']);
